"""add last_goal_celebration column to users table

Revision ID: 730a8e89a892
Revises: 284a6604ede8
Create Date: 2026-08-04 17:51:16.681073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '730a8e89a892'
down_revision: Union[str, Sequence[str], None] = '284a6604ede8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_goal_celebration_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_goal_celebration_sent_at')
    # ### end Alembic commands ###
