"""initial schema

Revision ID: 7820d7d04612
Revises: 
Create Date: 2026-08-04 00:07:24.183170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7820d7d04612'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mileage_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('business_rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('business_rate >= 0', name='ck_rate_non_negative'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('effective_date', name='uq_mileage_rate_effective_date')
    )
    op.create_index(op.f('ix_mileage_rates_effective_date'), 'mileage_rates', ['effective_date'], unique=False)
    op.create_index(op.f('ix_mileage_rates_id'), 'mileage_rates', ['id'], unique=False)
    op.create_table('tax_brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('filing_status', sa.Enum('single', 'married_filing_jointly', 'married_filing_separately', 'head_of_household', 'qualifying_surviving_spouse', name='filingstatus'), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_income IS NULL OR max_income > min_income', name='ck_income_range_valid'),
    sa.CheckConstraint('min_income >= 0', name='ck_min_income_positive'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_rate_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_brackets_filing_status'), 'tax_brackets', ['filing_status'], unique=False)
    op.create_index(op.f('ix_tax_brackets_id'), 'tax_brackets', ['id'], unique=False)
    op.create_index(op.f('ix_tax_brackets_year'), 'tax_brackets', ['year'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=500), nullable=True),
    sa.Column('revenuecat_user_id', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('email_verified', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role_enum'), server_default=sa.text("'user'"), nullable=False),
    sa.Column('filing_status', sa.Enum('single', 'married_filing_jointly', 'married_filing_separately', 'head_of_household', 'qualifying_surviving_spouse', name='filingstatus'), server_default=sa.text("'single'"), nullable=False),
    sa.Column('business_type', sa.Enum('gig_driver', 'freelancer', 'small_business', 'contractor', 'other', name='business_type_enum'), server_default=sa.text("'other'"), nullable=False),
    sa.Column('tax_method', sa.Enum('standard_mileage', 'actual_expenses', name='tax_method_enum'), server_default=sa.text("'standard_mileage'"), nullable=False),
    sa.Column('monthly_income_goal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('weekly_income_goal', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('estimated_vehicle_cost_per_mile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('minimum_profit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minimum_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('minimum_dollars_per_mile', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('preferred_max_distance', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('default_platform', sa.String(length=50), nullable=True),
    sa.Column('timezone', sa.String(length=50), server_default=sa.text("'America/New_York'"), nullable=False),
    sa.Column('currency', sa.Enum('USD', name='currency_enum'), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('distance_unit', sa.Enum('mi', 'km', name='distance_unit_enum'), server_default=sa.text("'mi'"), nullable=False),
    sa.Column('week_starts_on', sa.Enum('sunday', 'monday', name='week_starts_on_enum'), server_default=sa.text("'monday'"), nullable=False),
    sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('trip_reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('goal_reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('auto_trip_detection', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expo_push_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('revenuecat_user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('category', sa.Enum('advertising', 'bank_fees', 'commissions_fees', 'contract_labor', 'education', 'equipment', 'office_supplies', 'software', 'phone', 'internet', 'vehicle', 'fuel', 'car_wash', 'vehicle_maintenance', 'vehicle_repairs', 'vehicle_insurance', 'vehicle_registration', 'parking_tolls', 'travel', 'lodging', 'airfare', 'meals', 'rent', 'utilities', 'insurance', 'licenses_permits', 'professional_services', 'legal_fees', 'accounting', 'postage_shipping', 'interest', 'taxes_fees', 'marketing', 'memberships_subscriptions', 'home_office', 'repairs_maintenance', 'other', name='expense_category_enum'), nullable=False),
    sa.Column('incurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('business_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('receipt_url', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('merchant', sa.String(length=255), nullable=True),
    sa.CheckConstraint('amount > 0', name='check_amount_positive'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expenses_id'), 'expenses', ['id'], unique=False)
    op.create_index(op.f('ix_expenses_incurred_at'), 'expenses', ['incurred_at'], unique=False)
    op.create_index(op.f('ix_expenses_user_id'), 'expenses', ['user_id'], unique=False)
    op.create_index('ix_expenses_user_id_incurred_at', 'expenses', ['user_id', 'incurred_at'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_id'), 'sessions', ['id'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token'), 'sessions', ['refresh_token'], unique=True)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('original_transaction_id', sa.String(), nullable=False),
    sa.Column('latest_transaction_id', sa.String(), nullable=False),
    sa.Column('environment', sa.String(), nullable=False),
    sa.Column('purchase_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('original_transaction_id', name='uq_original_tx')
    )
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=False)
    op.create_table('trips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('start_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_lat', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('end_lng', sa.Numeric(precision=9, scale=6), nullable=False),
    sa.Column('start_address', sa.String(length=100), nullable=False),
    sa.Column('end_address', sa.String(length=100), nullable=False),
    sa.Column('distance_miles', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('platform', sa.Enum('UBER_EATS', 'SPARK', 'DOORDASH', 'LYFT', 'UBER', 'GRUBHUB', 'INSTACART', 'AMAZON_FLEX', 'SHIPT', 'OTHER', 'PERSONAL', name='trip_platform'), nullable=False),
    sa.Column('category', sa.Enum('BUSINESS', 'PERSONAL', name='trip_category'), nullable=False),
    sa.Column('deduction_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'start_time', 'end_time')
    )
    op.create_index(op.f('ix_trips_id'), 'trips', ['id'], unique=False)
    op.create_table('user_2fa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('secret', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_2fa_id'), 'user_2fa', ['id'], unique=False)
    op.create_table('user_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id')
    )
    op.create_index(op.f('ix_user_oauth_id'), 'user_oauth', ['id'], unique=False)
    op.create_index(op.f('ix_user_oauth_provider_user_id'), 'user_oauth', ['provider_user_id'], unique=False)
    op.create_table('income',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('source', sa.Enum('GIG_PLATFORM', 'BUSINESS', 'EMPLOYMENT', 'PASSIVE', 'OTHER', name='incometype'), nullable=False),
    sa.Column('platform', sa.Enum('UBER_EATS', 'SPARK', 'DOORDASH', 'LYFT', 'UBER', 'GRUBHUB', 'INSTACART', 'AMAZON_FLEX', 'SHIPT', 'OTHER', 'PERSONAL', name='tripplatform'), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_income_id'), 'income', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_income_id'), table_name='income')
    op.drop_table('income')
    op.drop_index(op.f('ix_user_oauth_provider_user_id'), table_name='user_oauth')
    op.drop_index(op.f('ix_user_oauth_id'), table_name='user_oauth')
    op.drop_table('user_oauth')
    op.drop_index(op.f('ix_user_2fa_id'), table_name='user_2fa')
    op.drop_table('user_2fa')
    op.drop_index(op.f('ix_trips_id'), table_name='trips')
    op.drop_table('trips')
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_sessions_refresh_token'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_expenses_user_id_incurred_at', table_name='expenses')
    op.drop_index(op.f('ix_expenses_user_id'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_incurred_at'), table_name='expenses')
    op.drop_index(op.f('ix_expenses_id'), table_name='expenses')
    op.drop_table('expenses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tax_brackets_year'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_id'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_filing_status'), table_name='tax_brackets')
    op.drop_table('tax_brackets')
    op.drop_index(op.f('ix_mileage_rates_id'), table_name='mileage_rates')
    op.drop_index(op.f('ix_mileage_rates_effective_date'), table_name='mileage_rates')
    op.drop_table('mileage_rates')
    # ### end Alembic commands ###
