"""rename weekly goal to daily goal

Revision ID: 7b36ed98b206
Revises: 1b21a96ba953
Create Date: 2026-08-26 22:45:55.116878

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b36ed98b206'
down_revision: Union[str, Sequence[str], None] = '1b21a96ba953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('daily_income_goal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.drop_column('users', 'weekly_income_goal')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weekly_income_goal', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('users', 'daily_income_goal')
    # ### end Alembic commands ###
