"""update mileage rates model

Revision ID: 8390fa8307c1
Revises: d66f0c983f69
Create Date: 2026-07-13 20:18:28.685414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8390fa8307c1'
down_revision: Union[str, Sequence[str], None] = 'd66f0c983f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mileage_rates', sa.Column('effective_date', sa.Integer(), nullable=False))
    op.add_column('mileage_rates', sa.Column('business_rate', sa.Numeric(precision=5, scale=4), nullable=False))
    op.drop_index(op.f('ix_mileage_rates_year'), table_name='mileage_rates')
    op.drop_constraint(op.f('uq_mileage_rate_year'), 'mileage_rates', type_='unique')
    op.create_index(op.f('ix_mileage_rates_effective_date'), 'mileage_rates', ['effective_date'], unique=False)
    op.create_unique_constraint('uq_mileage_rate_effective_date', 'mileage_rates', ['effective_date'])
    op.drop_column('mileage_rates', 'year')
    op.drop_column('mileage_rates', 'rate')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mileage_rates', sa.Column('rate', sa.NUMERIC(precision=5, scale=4), autoincrement=False, nullable=False))
    op.add_column('mileage_rates', sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('uq_mileage_rate_effective_date', 'mileage_rates', type_='unique')
    op.drop_index(op.f('ix_mileage_rates_effective_date'), table_name='mileage_rates')
    op.create_unique_constraint(op.f('uq_mileage_rate_year'), 'mileage_rates', ['year'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_mileage_rates_year'), 'mileage_rates', ['year'], unique=False)
    op.drop_column('mileage_rates', 'business_rate')
    op.drop_column('mileage_rates', 'effective_date')
    # ### end Alembic commands ###
