"""add weekly goal fields to user

Revision ID: 9c0a5a2e1d9c
Revises: 361379607b14
Create Date: 2026-07-25 17:17:33.239017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c0a5a2e1d9c'
down_revision: Union[str, Sequence[str], None] = '361379607b14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weekly_goal_type', sa.String(length=20), server_default=sa.text("'income'"), nullable=False))
    op.add_column('users', sa.Column('weekly_goal_amount', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weekly_goal_amount')
    op.drop_column('users', 'weekly_goal_type')
    # ### end Alembic commands ###
