"""add revenuecat to user

Revision ID: a4eb54781901
Revises: 648dbf6eaa59
Create Date: 2026-06-07 08:54:03.356747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a4eb54781901'
down_revision: Union[str, Sequence[str], None] = '648dbf6eaa59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriptions', sa.Column('provider_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_column('subscriptions', 'apple_response')
    op.add_column('users', sa.Column('revenuecat_user_id', sa.String(length=1000), nullable=True))
    op.create_unique_constraint(None, 'users', ['revenuecat_user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'revenuecat_user_id')
    op.add_column('subscriptions', sa.Column('apple_response', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('subscriptions', 'provider_response')
    # ### end Alembic commands ###
