"""change mileage effective_date to date

Revision ID: ba27e3680779
Revises: 8390fa8307c1
Create Date: 2026-07-13 22:44:26.885905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba27e3680779'
down_revision: Union[str, Sequence[str], None] = '8390fa8307c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
            "mileage_rates",
            "effective_date",
            existing_type=sa.INTEGER(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using="to_date(effective_date::text, 'YYYYMMDD')",
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
            "mileage_rates",
            "effective_date",
            existing_type=sa.INTEGER(),
            type_=sa.Date(),
            existing_nullable=False,
            postgresql_using="to_date(effective_date::text, 'YYYYMMDD')",
        )
    # ### end Alembic commands ###
