"""add tex_bracket with constraints

Revision ID: d442a49a065d
Revises: 81cdd4038eca
Create Date: 2026-04-30 07:02:26.703935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd442a49a065d'
down_revision: Union[str, Sequence[str], None] = '81cdd4038eca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tax_brackets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('filing_status', sa.String(), nullable=False),
    sa.Column('min_income', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('rate', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_income IS NULL OR max_income > min_income', name='ck_income_range_valid'),
    sa.CheckConstraint('min_income >= 0', name='ck_min_income_positive'),
    sa.CheckConstraint('rate >= 0 AND rate <= 1', name='ck_rate_valid'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_brackets_filing_status'), 'tax_brackets', ['filing_status'], unique=False)
    op.create_index(op.f('ix_tax_brackets_id'), 'tax_brackets', ['id'], unique=False)
    op.create_index(op.f('ix_tax_brackets_year'), 'tax_brackets', ['year'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tax_brackets_year'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_id'), table_name='tax_brackets')
    op.drop_index(op.f('ix_tax_brackets_filing_status'), table_name='tax_brackets')
    op.drop_table('tax_brackets')
    # ### end Alembic commands ###
