"""add user preferences fields

Revision ID: f0e68436504f
Revises: 9c0a5a2e1d9c
Create Date: 2026-07-27 22:25:57.143462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0e68436504f'
down_revision: Union[str, Sequence[str], None] = '9c0a5a2e1d9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('monthly_income_goal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('weekly_income_goal', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('estimated_vehicle_cost_per_mile', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('minimum_profit', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('minimum_hourly_rate', sa.Numeric(precision=10, scale=2), nullable=True))
    op.add_column('users', sa.Column('minimum_dollars_per_mile', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('users', sa.Column('preferred_max_distance', sa.Numeric(precision=6, scale=2), nullable=True))
    op.add_column('users', sa.Column('default_platform', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('timezone', sa.String(length=50), server_default=sa.text("'America/New_York'"), nullable=False))
    op.add_column('users', sa.Column('currency', sa.String(length=3), server_default=sa.text("'USD'"), nullable=False))
    op.add_column('users', sa.Column('distance_unit', sa.String(length=5), server_default=sa.text("'mi'"), nullable=False))
    op.add_column('users', sa.Column('week_starts_on', sa.String(length=10), server_default=sa.text("'monday'"), nullable=False))
    op.add_column('users', sa.Column('dashboard_default_view', sa.String(length=20), server_default=sa.text("'month'"), nullable=False))
    op.add_column('users', sa.Column('notifications_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('trip_reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('goal_reminders_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.add_column('users', sa.Column('auto_trip_detection', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.drop_column('users', 'weekly_goal_amount')
    op.drop_column('users', 'weekly_goal_type')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('weekly_goal_type', sa.VARCHAR(length=20), server_default=sa.text("'income'::character varying"), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('weekly_goal_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
    op.drop_column('users', 'auto_trip_detection')
    op.drop_column('users', 'goal_reminders_enabled')
    op.drop_column('users', 'trip_reminders_enabled')
    op.drop_column('users', 'notifications_enabled')
    op.drop_column('users', 'dashboard_default_view')
    op.drop_column('users', 'week_starts_on')
    op.drop_column('users', 'distance_unit')
    op.drop_column('users', 'currency')
    op.drop_column('users', 'timezone')
    op.drop_column('users', 'default_platform')
    op.drop_column('users', 'preferred_max_distance')
    op.drop_column('users', 'minimum_dollars_per_mile')
    op.drop_column('users', 'minimum_hourly_rate')
    op.drop_column('users', 'minimum_profit')
    op.drop_column('users', 'estimated_vehicle_cost_per_mile')
    op.drop_column('users', 'weekly_income_goal')
    op.drop_column('users', 'monthly_income_goal')
    # ### end Alembic commands ###
